name: FairApp

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches:
      - '*'
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  build:
    runs-on: macos-latest
    if: github.event_name != 'pull_request_target'
    steps:
      - uses: actions/checkout@v2
      #- run: swift test # cannot run until macos-11 is available
      - run: swift run indietool welcome
      - run: xcodebuild -workspace Fair-App.xcworkspace -configuration Release -scheme "FairApp" -sdk 'macosx' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - run: xcodebuild -workspace Fair-App.xcworkspace -configuration Release -scheme "FairApp" -sdk 'iphoneos' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

  deploy:
    name: Deploy ${{ github.event.pull_request.head.user.login }}
    runs-on: macos-latest
    if: github.event_name == 'pull_request_target' 
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Show Info
        run: |
          echo "TAG: ${{ github.event.inputs.branch }}"
          echo "APP: ${{ github.event.pull_request.head.user.login }}"
          echo "APP='${{ github.event.pull_request.head.user.login }}'" >> $env:GITHUB_ENV

      - name: Show Info
        run: |
          echo "APP2=${env.APP}"

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: swift run indietool welcome

      #- run: echo "PRODUCT_NAME=${env.PRORG/-/ }" >> $env:GITHUB_ENV
      #- run: echo "BUNDLE_ID=app.${env.PRORG/-/}" >> $env:GITHUB_ENV
      - run: echo "PRODUCT_NAME=$(echo ${env.PRORG} | tr '-' ' ')" >> $env:GITHUB_ENV
      - run: echo "BUNDLE_ID=app.$(echo ${env.PRORG} | tr -d '-')" >> $env:GITHUB_ENV

      #- name: Show Product
      #run: |
      #echo "BUILDING PRODUCT: ${env.PRODUCT_NAME}"

      - run: xcodebuild archive -workspace Fair-App.xcworkspace -configuration Release -scheme "FairApp" -sdk 'macosx' -archivePath "FairApp.xcarchive" CODE_SIGNING_REQUIRED=YES CODE_SIGNING_ALLOWED=YES 

      - name: "Export Archive"
        run: |
          mkdir "Exported/"
          echo '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>method</key><string>mac-application</string><key>signingStyle</key><string>automatic</string></dict></plist>' > "exportOptions.plist"
          xcodebuild \
            -verbose \
            -exportArchive \
            -archivePath "FairApp.xcarchive" \
            -exportPath "Exported/" \
            -exportOptionsPlist "exportOptions.plist"

          ditto -c -k --keepParent "Exported/FairApp.app" "Exported/FairApp.zip"

      # PRODUCT_NAME="${{ env.PRODUCT_NAME }}" PRODUCT_BUNDLE_IDENTIFIER="app.${{ env.BUNDLE_ID }}"

      #- run: xcodebuild -workspace Fair-App.xcworkspace -configuration Release -scheme "FairApp" -sdk 'iphoneos' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO 
      # PRODUCT_NAME="${{ github.event.pull_request.head.user.login }}"

      - uses: actions/upload-artifact@v2
        with:
          path: Exported/FairApp.zip

