name: FairApp

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches:
      - '*'
  schedule:
    - cron: '0 0,12 * * *'

# check for: github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      #- run: swift test # cannot run until macos-11 is available
      - run: swift run indietool welcome
      - run: xcodebuild -workspace Fair-App.xcworkspace -configuration Release -scheme "FairApp" -sdk 'macosx' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - run: xcodebuild -workspace Fair-App.xcworkspace -configuration Release -scheme "FairApp" -sdk 'iphoneos' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

  pr:
    name: Integrate PR
    runs-on: macos-latest
    if: (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') || (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
    steps:
    - name: Checkout Repository
      if: ${{ github.event_name != 'pull_request_target' }}
      uses: actions/checkout@v2.3.4
    - name: Checkout Repository PR
      if: ${{ github.event_name == 'pull_request_target' }}
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.event.pull_request.head.sha }}


